name: Publish Docker Images to GHCR

# This triggers the workflow whenever you push to the main branch
# or when you manually trigger it from the GitHub Actions tab
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  # This automatically evaluates to paulwaite87/WorldMap
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # Grants the workflow permission to write to your Packages registry
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and Push Main Python App
      - name: Build and push main app image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      # Build and Push UI
      - name: Build and push UI image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.ui
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-ui:latest

      # Build and Push Database
      - name: Build and push DB image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.db
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-db:latest